version: '3.9'

services:
  bazar:
    container_name: bazar
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://bazar_bd:3306/bazar?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: Lar@2024
    restart: always
    depends_on:
      - bazar_bd

  bazar_bd:
    container_name: bazar_bd
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Lar@2024
      MYSQL_PASSWORD: Lar@2024
      MYSQL_DATABASE: bazar
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10